name: flutter_qinglan
description: 青蓝霍尔库仑计电压电流电量表
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_blue_plus: ^1.4.0
  get: ^4.6.5
  permission_handler: ^10.2.0
  location: ^4.4.0
  device_info_plus: ^8.2.0
  logger: ^1.3.0
  percent_indicator: ^4.2.3
  fl_chart: ^0.62.0
  get_storage: ^2.1.1
  fluttertoast: ^8.2.1
  flutter_datetime_picker: ^1.5.1
  intl: ^0.18.1
  google_fonts: ^4.0.4
  excel: ^2.1.0
  path_provider: ^2.0.14
  flutter_easyloading: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

