import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'zh_CN': {
          '库仑计': '库仑计',
          '首页': '首页',
          '曲线图': '曲线图',
          '设置': '设置',
          '连接蓝牙': '连接蓝牙',
          '搜索': '搜索',
          '停止搜索': '停止搜索',
          '请打开蓝牙': '请打开蓝牙',
          '设备地址': '设备地址',
          '连接': '连接',
          '断开': '断开',
          '未连接': '未连接',
          '型号': '型号',
          '已连接': '已连接',
          '电压': '电压',
          '电流': '电流',
          '功率': '功率',
          '温度': '温度',
          '剩余能量': '剩余能量',
          '剩余容量': '剩余容量',
          '充满需用时:': '充满需用时:',
          '电流清零': '电流清零',
          '数据清零': '数据清零',
          '余量设定': '余量设定',
          '请输入电池余量': '请输入电池余量',
          '请先连接蓝牙': '请先连接蓝牙',
          '提示': '提示',
          '数值范围': '数值范围',
          '单位': '单位',
          '容量预设': '容量预设',
          '请输入电池容量': '请输入电池容量',
          '累计容量': '累计容量',
          '运行时间': '运行时间',
          '定时时间': '定时时间',
          '充电': '充电',
          '放电': '放电',
          '定时': '定时',
          '启动记录': '启动记录',
          '导出数据': '导出数据',
          '查看历史数据': '查看历史数据',
          '电压/温度/电流 实时曲线图': '电压/温度/电流 实时曲线图',
          '保存设置': '保存设置',
          "充电过压值": "充电过压值",
          "放电欠压值": "放电欠压值",
          "充电过流值": "充电过流值",
          "放电过流值": "放电过流值",
          "放电启动值": "放电启动值",
          "过温度保护值": "过温度保护值",
          "低温恢复值": "低温恢复值",
          "继电器延时": "继电器延时",
          "继电器工作模式": "继电器工作模式",
          "上电默认输出": "上电默认输出",
          "温度控制": "温度控制",
          "语言": "语言",
          "定时时间值": "定时时间值",
          "定时模式": "定时模式",
          "充电电流系数微调": "充电电流系数微调",
          "放电电流系数微调": "放电电流系数微调",
          "通讯地址码": "通讯地址码",
          "电流归零值": "电流归零值",
          "请输入充电过压值": "请输入充电过压值",
          "请输入放电欠压值": "请输入放电欠压值",
          "请输入充电过流值": "请输入充电过流值",
          "请输入放电过流值": "请输入放电过流值",
          "请输入放电启动值": "请输入放电启动值",
          "请输入过温度保护值": "请输入过温度保护值",
          "请输入低温恢复值": "请输入低温恢复值",
          "请输入继电器延时": "请输入继电器延时",
          "请选择继电器工作模式": "请选择继电器工作模式",
          "请选择上电默认输出": "请选择上电默认输出",
          "请选择温控模式": "请选择温控模式",
          "控制充电继电器": "控制充电继电器",
          "控制放电继电器": "控制放电继电器",
          "请选择语言": "请选择语言",
          "请选择定时时间值": "请选择定时时间值",
          "选择日期": "选择日期",
          "请选择定时模式": "请选择定时模式",
          "请输入充电电流系数微调": "请输入充电电流系数微调",
          "请输入放电电流系数微调": "请输入放电电流系数微调",
          "请输入通讯地址码": "请输入通讯地址码",
          "请输入电流归零值": "请输入电流归零值",
          "选择语言": "选择语言",
          "确定": "确定",
          "取消": "取消",
          "确定电流清零吗？": "确定电流清零吗？",
          "确定数据清零吗？": "确定数据清零吗？",
          "工作模式一": "工作模式一",
          "工作模式二": "工作模式二",
          "工作模式三": "工作模式三",
          "工作模式四": "工作模式四",
          "工作模式五": "工作模式五",
          "时": "时",
          "分": "分",
          "秒": "秒",
          "停止记录": "停止记录",
          "是否先删除历史数据?": "是否先删除历史数据?",
          "正在记录数据，请停止记录之后再导出...": "正在记录数据，请停止记录之后再导出...",
          "暂未找到设备": "暂未找到设备",
          "导出成功": "导出成功",
          "半小时": "半小时",
          "1小时": "1小时",
          "2小时": "2小时",
          "3小时": "3小时",
          "5小时": "5小时",
          "10小时": "10小时",
          "倍": "倍",
          "连接设备之前需打开蓝牙，是否要打开？": "连接设备之前需打开蓝牙，是否要打开？",
          "前往打开": "前往打开",
        },
        "zh_TW": {
          '库仑计': '庫倫計',
          '首页': '首頁',
          '曲线图': '曲線圖',
          '设置': '設置',
          '请打开蓝牙': '請打開藍牙',
          '连接蓝牙': '連接藍牙',
          '搜索': '搜索',
          '停止搜索': '停止搜索',
          '设备地址': '設備地址',
          '连接': '連接',
          '断开': '斷開',
          '未连接': '未連接',
          '型号': '型號',
          '已连接': '已連接',
          '电压': '電壓',
          '电流': '電流',
          '功率': '功率',
          '温度': '溫度',
          '剩余能量': '剩餘能量',
          '剩余容量': '剩餘容量',
          '充满需用时:': '充滿需用時:',
          '电流清零': '電流清零',
          '数据清零': '數據清零',
          '余量设定': '餘量設定',
          '请输入电池余量': '請輸入電池餘量',
          '请先连接蓝牙': '請先連接藍牙',
          '提示': '提示',
          '数值范围': '數值範圍',
          '单位': '單位',
          '容量预设': '容量預設',
          '请输入电池容量': '請輸入電池容量',
          '累计容量': '累計容量',
          '运行时间': '運行時間',
          '定时时间': '定時時間',
          '充电': '充電',
          '放电': '放電',
          '定时': '定時',
          '启动记录': '啟動記錄',
          '导出数据': '導出數據',
          '查看历史数据': '查看歷史數據',
          '电压/温度/电流 实时曲线图': '電壓/溫度/電流 實時曲線圖',
          '保存设置': '保存設置',
          "充电过压值": "充電過壓值",
          "放电欠压值": "放電欠壓值",
          "充电过流值": "充電過流值",
          "放电过流值": "放電過流值",
          "放电启动值": "放電啟動值",
          "过温度保护值": "過溫度保護值",
          "低温恢复值": "低溫恢復值",
          "继电器延时": "繼電器延時",
          "继电器工作模式": "繼電器工作模式",
          "上电默认输出": "上電默認輸出",
          "温度控制": "溫度控制",
          "语言": "語言",
          "定时模式": "定時模式",
          "充电电流系数微调": "充電電流係數微調",
          "放电电流系数微调": "放電電流係數微調",
          "通讯地址码": "通訊地址碼",
          "电流归零值": "電流歸零值",
          "请输入充电过流值": "請輸入充電過流值",
          "请输入放电过流值": "請輸入放電過流值",
          "请输入放电启动值": "請輸入放電啟動值",
          "请输入过温度保护值": "請輸入過溫度保護值",
          "请输入低温恢复值": "請輸入低溫恢復值",
          "请输入继电器延时": "請輸入繼電器延時",
          "请输入充电过压值": "請輸入充電過壓值",
          "请输入放电欠压值": "請輸入放電欠壓值",
          "请选择继电器工作模式": "請選擇繼電器工作模式",
          "请选择上电默认输出": "請選擇上電默認輸出",
          "请选择温控模式": "請選擇溫控模式",
          "请输入定时模式": "請輸入定時模式",
          "选择日期": "選擇日期",
          "控制充电继电器": "控制充電繼電器",
          "控制放电继电器": "控制放電繼電器",
          "请输入充电电流系数微调": "請輸入充電電流係數微調",
          "请输入放电电流系数微调": "請輸入放電電流係數微調",
          "请输入通讯地址码": "請輸入通訊地址碼",
          "请输入电流归零值": "請輸入電流歸零值",
          "选择语言": "選擇語言",
          "确定": "確定",
          "取消": "取消",
          "确定电流清零吗？": "確定電流清零嗎？",
          "确定数据清零吗？": "確定數據清零嗎？",
          "工作模式一": "工作模式一",
          "工作模式二": "工作模式二",
          "工作模式三": "工作模式三",
          "工作模式四": "工作模式四",
          "工作模式五": "工作模式五",
          "时": "時",
          "分": "分",
          "秒": "秒",
          "停止记录": "停止記錄",
          "是否先删除历史数据?": "是否先刪除歷史數據?",
          "正在记录数据，请停止记录之后再导出...": "正在記錄數據，請停止記錄之後再導出...",
          "暂未找到设备": "暫未找到設備",
          "导出成功": "導出成功",
          "半小时": "半小時",
          "1小时": "1小時",
          "2小时": "2小時",
          "3小时": "3小時",
          "5小时": "5小時",
          "10小时": "10小時",
          "倍": "倍",
          "连接设备之前需打开蓝牙，是否要打开？": "連接設備之前需打開藍牙，是否要打開？",
          "前往打开": "前往打開",
        },
        'en_US': {
          '库仑计': 'Coulombmeter',
          '首页': 'Home',
          '曲线图': 'Graph',
          '设置': 'Settings',
          '请打开蓝牙': 'Please turn on Bluetooth',
          '连接蓝牙': 'Connect Bluetooth',
          '设备地址': 'Device Address',
          '搜索': 'Search',
          '停止搜索': 'Stop',
          '连接': 'Connect',
          '断开': 'Disconnect',
          '未连接': 'Not Connected',
          '型号': 'Model',
          '已连接': 'Connected',
          '电压': 'Voltage',
          '电流': 'Current',
          '功率': 'Power',
          '温度': 'Temperature',
          '剩余能量': 'Remaining Energy',
          '剩余容量': 'Remaining Capacity',
          '充满需用时:': 'Full time:',
          '电流清零': 'Current clear',
          '数据清零': 'Data clear',
          '余量设定': 'Capacity setting',
          '请输入电池余量': 'Please enter the battery capacity',
          '请先连接蓝牙': 'Please connect Bluetooth first',
          '提示': 'Tips',
          '数值范围': 'Value range',
          '单位': 'Unit',
          '容量预设': 'Capacity setting',
          '请输入电池容量': 'Please enter the battery capacity',
          '累计容量': 'Cumulative capacity',
          '运行时间': 'Running time',
          '定时时间': 'Timing time',
          '充电': 'Charge',
          '放电': 'Discharge',
          '定时': 'Timing',
          '启动记录': 'Start record',
          '导出数据': 'Export data',
          '查看历史数据': 'View historical data',
          '电压/温度/电流 实时曲线图': 'Voltage/temperature/current real-time curve',
          '保存设置': 'Save settings',
          "充电过压值": "Overvoltage value",
          "放电欠压值": "Undervoltage value",
          "充电过流值": "Overcurrent value",
          "放电过流值": "Overcurrent value",
          "放电启动值": "Discharge start value",
          "过温度保护值": "Overtemperature protection value",
          "低温恢复值": "Low temperature recovery value",
          "继电器延时": "Relay delay",
          "继电器工作模式": "Relay working mode",
          "上电默认输出": "Default output on power up",
          "温度控制": "Temperature control",
          "语言": "Language",
          "定时时间值": "Timing time value",
          "定时模式": "Timing mode",
          "充电电流系数微调": "Fine-tuning of charging current coefficient",
          "放电电流系数微调": "Fine-tuning of discharge current coefficient",
          "通讯地址码": "Communication address code",
          "电流归零值": "Current zero value",
          "请输入充电过压值": "Please enter the overvoltage value for charging",
          "请输入放电欠压值": "Please enter the undervoltage value for discharging",
          "请输入充电过流值": "Please enter the overcurrent value for charging",
          "请输入放电过流值": "Please enter the overcurrent value for discharging",
          "请输入放电启动值": "Please enter the discharging start value",
          "请输入过温度保护值": "Please enter the over-temperature protection value",
          "请输入低温恢复值": "Please enter the low-temperature recovery value",
          "请输入继电器延时": "Please enter the relay delay time",
          "请选择继电器工作模式": "Please select the relay working mode",
          "请选择上电默认输出": "Please select the default output at power-on",
          "请选择温控模式": "Please select the temperature control mode",
          "请选择语言": "Please select the language",
          "请选择定时时间值": "Please select the timing time value",
          "选择日期": "Select date",
          "请选择定时模式": "Please select the timing mode",
          "控制充电继电器": "Control charging relay",
          "控制放电继电器": "Control discharging relay",
          "请输入充电电流系数微调":
              "Please enter the fine-tuning coefficient for charging current",
          "请输入放电电流系数微调":
              "Please enter the fine-tuning coefficient for discharging current",
          "请输入通讯地址码": "Please enter the communication address code",
          "请输入电流归零值": "Please enter the current zero value",
          "选择语言": "Select language",
          "确定": "Confirm",
          "取消": "Cancel",
          "确定电流清零吗？": "Are you sure to reset the current?",
          "确定数据清零吗？": "Are you sure to reset the data?",
          "工作模式一": "Working mode one",
          "工作模式二": "Working mode two",
          "工作模式三": "Work Mode Three",
          "工作模式四": "Work Mode Four",
          "工作模式五": "Work Mode Five",
          "时": "H",
          "分": "M",
          "秒": "S",
          "停止记录": "Stop recording",
          "是否先删除历史数据?": "Delete historical data first?",
          "正在记录数据，请停止记录之后再导出...":
              "Data is being recorded, please stop recording before exporting...",
          "暂未找到设备": "Device not found",
          "导出成功": "Export successful",
          "半小时": "Half an hour",
          "1小时": "1 hour",
          "2小时": "2 hour",
          "3小时": "3 hour",
          "5小时": "5 hour",
          "10小时": "10 hour",
          "倍": "times",
          "连接设备之前需打开蓝牙，是否要打开？":
              "Bluetooth needs to be turned on before connecting, do you want to turn it on?",
          "前往打开": "Go to open",
        }
      };
}
